[ {
}, {
  "patchName" : "Custom branding Music name",
  "options" : [ {
    "key" : "MusicLongName",
    "value" : "YouTube Music"
  }, {
    "key" : "MusicShortName",
    "value" : "YouTube Music"
  } ]
}, {
  "patchName" : "Custom branding YouTube name",
  "options" : [ {
    "key" : "YouTubeAppName",
    "value" : "YouTube"
  } ]
}, {
  "patchName" : "Custom double tap length",
  "options" : [ {
    "key" : "DoubleTapLengthArrays",
    "value" : "3, 5, 10, 15, 20, 30, 60, 120, 180"
  } ]
}, {
  "patchName" : "Custom package name",
  "options" : [ {
    "key" : "YouTubePackageName",
    "value" : "app.rvx.youtube"
  }, {
    "key" : "MusicPackageName",
    "value" : "app.rvx.youtube.music"
  } ]
}, {
  "patchName" : "Reddit settings",
  "options" : [ {
    "key" : "Reddit Settings",
    "value" : false
  } ]
}, {
  "patchName" : "Theme",
  "options" : [ {
    "key" : "darkThemeBackgroundColor",
    "value" : "@android:color/black"
  } ]
} ]
